name: App Deployment & Automation Trigger

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  trigger-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Fixed parameter name from github-token to token
      - name: Wait for Vercel Deployment Link
        uses: vercel/wait-for-deployment-action@main
        id: vercel_deploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Renamed correctly

      # 2. This triggers your automation repository path using QAAUTOMATION
      - name: Trigger Automation Pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.QAAUTOMATION }}
          repository: vikashsaw/PlaywrightAutomationFramework
          event-type: trigger-automation-tests
          client-payload: '{"app_url": "${{ steps.vercel_deploy.outputs.deployment-url }}"}'
